DefaultContentLanguage = "zh"
dateFormat = "2006-01-02 15:04:05"
description = "Build cool things"
enableEmoji = true
enableGitInfo = true
languageCode = "zh-cn"
theme = "diary"
title = "Zenlab Blog"
baseURL = "https://blog.zenlab.top/"
relativeURLs = true



[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "github"
tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.cjk]
enable = true
eastAsianLineBreaks = true
escapedSpace = true

[params]
# enableGitalk = false
enableOpenGraph = true
enableTwitterCards = true
title = "Zenlab Blog"
description = "Build cool things"
enableMathJax = true
enableLaTeX=true
enableMermaid = true
enableReadingTime = true
# favicon = "👋"  # emoji favicon 使用下方内联方式
subtitle = "Build cool things"
enableTwikoo = false
homePageSection = "blog"

# [params.gitalk]
# owner = "user"
# repo = "repo name"
# client_id = "your client id"
# client_secret = "your client secret"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"


[[menu.main]]
name = "文章📖"
url = "/blog"
weight = 1

[[menu.main]]
name = "分类📌"
url = "/categories"
weight = 2

[[menu.main]]
name = "标签🏷️"
url = "/tags"
weight = 3

[[menu.main]]
name = "归档📃"
url = "/archive"
weight = 4

[[menu.main]]
name = "关于👋"
url = "/about"
weight = 5

[[menu.main]]
name = "RSS📢"
url = "/index.xml"
weight = 6

[[menu.footer]]
name = "GitHub"
url = "https://github.com/clchen-dev"
weight = 1

[[menu.footer]]
name = "Mail"
url = "mailto:mail@zenlab.top"
weight = 2
